sudo: required
dist: trusty # (14.04)
# xenial (16.04) is not supported yet

language: cpp
compiler:
  - clang

git:
  depth: 1

before_install:
  - sudo apt-get -y install build-essential libtool make cmake cmake-data openssl
  - sudo apt-get -y install libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev libace-dev
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init
  
install:
  - cd ..
  - git clone --depth=1 --branch=master https://github.com/talamortis/OregonCore.git oregoncore
  - mv OregonCore-Modules oregoncore/modules
  - cd oregoncore
  - git submodule update --init --recursive

  - mysql -uroot -e 'create database test_mysql;'
  - cd bin
  - cmake .. -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++" -DSERVERS=1 -DTOOLS=1 -DSCRIPTS=1 -DWITH_DOCS=1 -DWITH_WARNINGS=0 -DWITH_COREDEBUG=0
  - cd ..

script:
  - cd $TRAVIS_BUILD_DIR/sql
  - sudo mysql -u root --password='' < create/create_mysql.sql
  - mysql -u oregon -poregon realmd < base/realmd.sql
  - mysql -u oregon -poregon characters < base/characters.sql
  # mysql -u oregon -poregon world < base/world.sql
  - curl -L --retry 3 -o database_17_11_19.zip https://github.com/talamortis/OregonCore/releases/download/v1.0/database_17_11_19.zip
  - unzip database_17_11_19.zip
  - mysql -u oregon -poregon world < database_17_11_19.sql
  - cat updates/realmd/*.sql | mysql -u oregon -poregon realmd
  - cat updates/characters/*.sql | mysql -u oregon -poregon characters
  - cat updates/world/*.sql | mysql -u oregon -poregon world